- hosts: all
  become: 'yes'
  vars_files:
    - vars.yml
  tasks:
    - name: "test_query"
      community.postgresql.postgresql_query:
        db: postgres
        query: "select * from pg_database;"
      become_user: postgres
      register: query_res
    - debug:
        var: query_res
