- name: Sample test playbook
  hosts: all
  become: 'yes'
  gather_facts: no
  tasks:
    - name: "list long running queries"
      postgresql_query:
       db: postgres
       query: " SELECT
                      pid,
                      datname,
                      now() - pg_stat_activity.query_start AS duration,
                      query,
                      state
                      FROM pg_stat_activity
                      WHERE  (now() - pg_stat_activity.query_start) > interval '5 minutes'; "
      become_user: postgres
      register: lrq_result
      tags:
       - lrq_query

    - debug:
        msg: "{{ ansible_play_hosts | map('extract', hostvars, 'lrq_result') | map(attribute='query_result') | list  }}"
       
      run_once: yes
