- name: Sample test playbook
  hosts: all
  become: 'yes'
  tasks:
    - name: "long running queries"
      postgresql_query:
       db: postgres
       query: "select * from pg_extension where extname='pgstattuple';"
      become_user: postgres
      register: two_phase_results
      tags:
       - long_query_list

    - debug:
       var: two_phase_results
