- name: Sample test playbook
  hosts: all
  become: 'yes'
  gather_facts: yes
  tasks:
    - name: "list database in 5432"
      postgresql_query:
       db: postgres
       query: "select * from pg_database;"
      become_user: postgres
      register: db_res_5432
      tags:
       - query_5445

    - debug:
       var: db_res_5432 | json_query('query_result[*].datname')
