- name: Sample test playbook
  hosts: thinkpad
  become: 'yes'
  gather_facts: yes
  tasks:
    - name: "list database"
      postgresql_query:
       db: postgres
       query: "select * from pg_database;"
      become_user: postgres
      register: two_phase_results
      tags:
       - long_query_list

    - debug:
       var: two_phase_results
