- name: Sample test playbook
  hosts: thinkpad
  become: 'yes'
  gather_facts: yes
  tasks:
    - name: "list database in 5432"
      postgresql_query:
       db: postgres
       port: 5432
       query: "select * from pg_database;"
      become_user: postgres
      register: db_res_5432
      tags:
       - query_5445

    - debug:
       var: { db_res_5432.query_result.0.datname }

    - name: "list database in 5445"
      postgresql_query:
       db: postgres
       port: 5445
       query: "select * from pg_database;"
      become_user: postgres
      register: db_res_5445
      tags:
       - query_5445

    - debug:
       var: { db_res_5445.query_result.0.datname }
