---
- hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "test query"
      community.postgresql.postgresql_query:
       db: postgres
       query: "select * from pg_database;"
      become_user: postgres
      register: query_res

    - debug:
       var: query_res
